spring:
  security:
    oauth2:
      client:
        registration:
          facebook: 
            client-id : 1061540851955528 
            client-secret : aa47c72d9d97432c49bb6391201aeb65 
          google:
            client-id : 505218284104-mhk8prkb5s8tjh4c147tc0hsj3cnl65s.apps.googleusercontent.com
            client-secret: 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
#          github:  